[package]
name = "index"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[build-dependencies]
cbindgen = "0.29"


[profile.release]
lto = true
opt-level = 3
codegen-units = 1


[[bin]]
name = "sqlite"
path = "bin/sqlite.rs"

[[bin]]
name = "store_comments"
path = "bin/store_comments.rs"

[[bin]]
name = "store_comments_per_file"
path = "bin/store_comments_per_file.rs"

[[bin]]
name = "sqlite_benchmark"
path = "bin/sqlite_insertion_benchmark.rs"

[[bin]]
name = "sqlite_benchmark_concise"
path = "bin/sqlite_benchmark_concise.rs"

[[bin]]
name = "sqlite_reading_benchmark"
path = "bin/sqlite_reading_benchmark.rs"

[[bin]]
name = "sqlite_simple_reading_benchmark"
path = "bin/sqlite_simple_reading_benchmark.rs"

[dependencies]
rusqlite = { version = "0.37.0", features = ["bundled"] }
rand = "0.8"