[package]
name = "index"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ahash = "0.8"
hashbrown = "0.14"

[build-dependencies]
cbindgen = "0.29"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
