[package]
name = "index"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.29"

[dependencies]
libc = "0.2.174"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
