[package]
name = "index-sys"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
index = { path = "../index" }
libc = "0.2.174"

[build-dependencies]
cbindgen = "0.29"

[lints]
workspace = true
