name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"

      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable clippy rustfmt

      - name: Set up Ruby
        uses: ruby/setup-ruby@d5f787ce339eb0767271bc01d922e85644c2c8ab # v1.280.0
        with:
          bundler-cache: true

      - name: Lint
        run: bundle exec rake lint
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [shopify-ubuntu-latest, macos-latest, shopify-windows-latest]
        ruby: ["3.3", "3.4", "4.0"]
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: "recursive"

      - name: Set up Ruby
        uses: ruby/setup-ruby@d5f787ce339eb0767271bc01d922e85644c2c8ab # v1.280.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Restore Rust compile cache
        id: rust-compile-cache-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-rust

      - name: Run Rust tests
        run: bundle exec rake cargo_test

      - name: Run Ruby tests
        run: bundle exec rake test

      - name: Save Rust compile cache
        id: rust-compile-cache-save
        uses: actions/cache/save@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ steps.rust-compile-cache-restore.outputs.cache-primary-key }}
