name: Memleak

on:
  push:
    paths:
      - ".github/workflows/memleak.yml"
      - "rust/**"
      - "ext/**"
  pull_request:
    paths:
      - ".github/workflows/memleak.yml"
      - "rust/**"
      - "ext/**"

jobs:
  memleak:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@d5f787ce339eb0767271bc01d922e85644c2c8ab # v1.280.0
        with:
          bundler-cache: true

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run tests capturing leaks with `memory` sanitizer
        run: SANITIZER=memory bundle exec rake ruby_test:valgrind

      - name: Run tests capturing leaks with `leak` sanitizer
        run: SANITIZER=leak bundle exec rake ruby_test:valgrind

      - name: Run tests capturing leaks with `thread` sanitizer
        run: SANITIZER=thread bundle exec rake ruby_test:valgrind
