name: Memleak

on:
  push:
    paths:
      - ".github/workflows/memleak.yml"
      - "rust/**"
      - "ext/**"
  pull_request:
    paths:
      - ".github/workflows/memleak.yml"
      - "rust/**"
      - "ext/**"

jobs:
  memleak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@90be1154f987f4dc0fe0dd0feedac9e473aa4ba8 # v1.286.0
        with:
          bundler-cache: true

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Install Rust tools
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run tests capturing leaks with `memory` sanitizer
        run: SANITIZER=memory bundle exec rake ruby_test:valgrind

      - name: Run tests capturing leaks with `leak` sanitizer
        run: SANITIZER=leak bundle exec rake ruby_test:valgrind

      - name: Run tests capturing leaks with `thread` sanitizer
        run: SANITIZER=thread bundle exec rake ruby_test:valgrind
